### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by reelsense** [oxguy3/oxguy3.github.io#1]
ITM! What's the license on your site code? It's all in one HTML file. It would be nice to use.
Thank you for helping with the [NAsummaries](https://github.com/K8TIY/NASummaries/issues/2). Thank you for your courage.

**Comment by hayleox** [comment]
Hmm, I guess I'm fine with the code being MIT License. I reserve all rights
for the written substance of my resume/projects pages, but I can't imagine
why anyone would want to reuse my resume anyway.

**Comment by reelsense** [comment]
Thank you for the response.
